### ISSUE TITLE
Allow passing in an existing `asyncpg.Connection`

### ISSUE THREAD

**Issue by adriangb** [RonquilloAeon/migri#51]
Use case: I want to run migrations programmatically, either during app startup or during tests. In either case, I have an `asyncp.Pool` already, so it'd be nice to avoid the oveheread of creating new connections. This should be achievable by adding an argument to the constructor for `PostgreSQLConnection`.

**Comment by RonquilloAeon** [comment]
@adriangb are you using `apply_migrations()` to run your migrations? It can already accept an instance of `asyncpg.Connection`. I'm not sure if the `PoolConnectionProxy` returned by `pool.acquire()` is compatible with `Connection` or if it inherits from a common parent class. I'll take a closer look at the code.

**Comment by adriangb** [comment]
Hmm could you give me an example? I thought it was hard coded here:

https://github.com/RonquilloAeon/migri/blob/29f8adbcfabd5c188c836741e7d06b628c99f88c/migri/backends/postgresql.py#L33

**Comment by adriangb** [comment]
Here's what I'm currently doing: https://github.com/adriangb/xpresso-gke-demo/blob/realworld/app/app/db/migrations/run.py

**Comment by RonquilloAeon** [comment]
@adriangb my bad, I was looking at the deprecated functionality. Indeed, the `ConnectionBackend` can be updated to accept an established connection. One way I can think of handling this is by adding constructor class methods on the backend classes. I'll spend some more time thinking on it though.

Here's an example of how I'm handling the scenario you shared. And like you, migri has its own connection rather than using the app's connection (hence why I run `db.connect()` after the migrations. BTW, you should be able to use the `get_connection()` helper class, though it's not a big deal if you instantiate `PostgreSQLConnection` directly.

https://github.com/RonquilloAeon/fastapi-migrations/blob/master/src/main.py

**Comment by adriangb** [comment]
Yeah it's honestly not a bit deal for a live app, it's more of an issue for tests because establishing a new connection is slow. I'll send a PR.
